product_list ="""
- Auto loan: [Optimal Refinance Auto Loan, Prime Lease Buyout, Elite Lease Buyout, Select Used Car Loan, Value Auto Loan, Advanced Electric Vehicle Loan, Exclusive Used Car Loan, Prestige Refinance Auto Loan, Premium Refinance Auto Loan, Standard Lease Buyout]  
- Checking Account: [Ultimate Student Checking, Preferred Interest Checking, Premium Basic Checking, Deluxe Basic Checking, Exclusive Business Checking, Classic Checking, Basic Student Checking, Standard Basic Checking, Premium Student Checking, Deluxe Interest Checking]  
- Credit card: [Preferred Cash Back Card, Platinum Student Card, Optimal Student Card, Value Secured Card, Standard Student Card, Select Student Card, Classic Student Card, Smart Platinum Card, Prime Rewards Card, Prime Student Card, Premier Cash Back Card, Elite Cash Back Card, Gold Rewards Card, Premier Cash Back Card, Flex Rewards Card, Advanced Travel Card, Prime Rewards Card, Classic Business Card, Freedom Cash Back Card, Exclusive Secured Card]  
- Insurance: [Smart Auto Insurance, Signature Home Insurance, Premium Home Insurance, Preferred Life Insurance, Prestige Home Insurance, Exclusive Life Insurance, Classic Life Insurance, Exclusive Renters Insurance, Elite Home Insurance, Prime Home Insurance]  
- Investment: [Premier ETF, Preferred Retirement Fund, Signature Mutual Fund, Elite ETF, Standard Retirement Fund, Basic Bond Fund, Platinum Retirement Fund, Standard Target Date Fund, Signature Index Fund, Platinum Mutual Fund]  
- Mortgage: [Deluxe FHA Loan, Signature VA Loan, Classic Jumbo Mortgage, Flex Fixed-Rate Mortgage, Value FHA Loan, Elite Adjustable-Rate Mortgage, Premier Fixed-Rate Mortgage, Select FHA Loan, Platinum Jumbo Mortgage, Ultimate Fixed-Rate Mortgage]  
- Personal loan: [Basic Wedding Loan, Gold Wedding Loan, Elite Debt Consolidation Loan, Freedom Home Improvement Loan, Ultimate Personal Loan, Standard Vacation Loan, Prestige Wedding Loan, Signature Personal Loan, Advantage Debt Consolidation Loan, Smart Debt Consolidation Loan, Basic Vacation Loan, Prime Emergency Loan, Platinum Wedding Loan, Flex Vacation Loan, Flex Home Improvement Loan]  
- Savings Account[Prime Savings, Exclusive Money Market, Premium Goal Savings, Deluxe Money Market, Advanced Kids Savings, Silver IRA, Premier Goal Savings, Gold Goal Savings, Value Savings, Optimal High-Yield Savings, Value Certificate of Deposit, Preferred Savings, Advanced Kids Savings, Advanced High-Yield Savings, Standard Kids Savings]
"""